/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package citcardtopup;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.nio.ByteBuffer;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.smartcardio.Card;
import javax.smartcardio.CardChannel;
import javax.smartcardio.CardException;
import javax.smartcardio.CardTerminal;
import javax.smartcardio.TerminalFactory;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.xml.datatype.DatatypeConfigurationException;
import javax.xml.datatype.DatatypeFactory;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 *
 * @author user
 */
public class RefundFrame extends javax.swing.JFrame {

    private CardTerminal acr122uCardTerminal = null;

    /**
     * Creates new form RefundFrame
     */
    public RefundFrame() {
        initComponents();
    }

    public RefundFrame(String username) {
        initComponents();
        lbStaff.setText(username);
        lbMsg.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbAmount = new javax.swing.JLabel();
        tbAmount = new javax.swing.JLabel();
        lbTitle = new javax.swing.JLabel();
        lbWelcome = new javax.swing.JLabel();
        lbStaff = new javax.swing.JLabel();
        btnRefund = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lbCardNo = new javax.swing.JLabel();
        tbCardNo = new javax.swing.JTextField();
        lbMsg = new javax.swing.JLabel();
        lbAmount1 = new javax.swing.JLabel();
        tbAmount1 = new javax.swing.JLabel();
        lbLogout = new javax.swing.JLabel();

        lbAmount.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbAmount.setText("Amount: ");

        tbAmount.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lbTitle.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        lbTitle.setText("Input Card ID to Refund");

        lbWelcome.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbWelcome.setText("ID:");

        lbStaff.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbStaff.setText("Station Staff");

        btnRefund.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnRefund.setText("Refund");
        btnRefund.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefundActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lbCardNo.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbCardNo.setText("Card Number: ");

        tbCardNo.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        tbCardNo.setPreferredSize(new java.awt.Dimension(230, 30));

        lbMsg.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbMsg.setForeground(new java.awt.Color(204, 0, 0));
        lbMsg.setText("msg");

        lbAmount1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbAmount1.setText("Amount: ");

        tbAmount1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        lbLogout.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbLogout.setText("Log Out");
        lbLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLogoutMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbLogoutMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbWelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbStaff)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbLogout)
                .addGap(69, 69, 69))
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbAmount1)
                    .addComponent(lbCardNo)
                    .addComponent(lbMsg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(18, 18, 18)
                        .addComponent(btnRefund)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tbAmount1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tbCardNo, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
                        .addGap(202, 202, 202))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbStaff)
                    .addComponent(lbWelcome)
                    .addComponent(lbLogout))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTitle)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCardNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbCardNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lbAmount1))
                    .addComponent(tbAmount1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbMsg)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefund)
                    .addComponent(btnBack))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.setVisible(false);
        SelectFrame sFrame = new SelectFrame(lbStaff.getText());
        sFrame.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
//            ActionListener actionListenerQuitOnNoReaderAttached = new ActionListener() {
//                public void actionPerformed(ActionEvent event) {
//                    quitOnNoReaderAttached();
//                }
//            };

//            Timer timerQuitOnNoReaderAttached = new Timer(5000, actionListenerQuitOnNoReaderAttached);
//            timerQuitOnNoReaderAttached.setRepeats(false);
//            timerQuitOnNoReaderAttached.start();
            TerminalFactory terminalFactory = TerminalFactory.getDefault();

            if (!terminalFactory.terminals().list().isEmpty()) {
                for (CardTerminal cardTerminal : terminalFactory.terminals().list()) {
                    if (cardTerminal.getName().contains("ACS ACR122")) {
                        acr122uCardTerminal = cardTerminal;

                        break;
                    }
                }

                if (acr122uCardTerminal != null) {
                    //timerQuitOnNoReaderAttached.stop();

                    //jTextFieldAttachedReader.setText(acr122uCardTerminal.getName());
                    ActionListener actionListenerCheckCardPresent = new ActionListener() {
                        public void actionPerformed(ActionEvent event) {
                            checkCardPresent();
                        }
                    };

                    Timer timerCheckCardPresent = new Timer(5000, actionListenerCheckCardPresent);
                    timerCheckCardPresent.setRepeats(true);
                    timerCheckCardPresent.start();

                    //JOptionPane.showMessageDialog(this, "ACS ACR122U Reader detected successfully", "Reader Detected Successful", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Unable to detect ACS ACR122U Reader", "Reader Detected Failure", JOptionPane.ERROR_MESSAGE);
                    this.setVisible(false);
                    this.dispose();
                }
            } else {
                JOptionPane.showMessageDialog(this, "No card reader is attached", "Reader Detected Failure", JOptionPane.ERROR_MESSAGE);
                this.setVisible(false);
                this.dispose();
            }
        } catch (Exception ex) {
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void btnRefundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefundActionPerformed
        if (!tbCardNo.getText().equals("No Card Detected!") && tbAmount.getText() != null && !tbCardNo.getText().equals("")) {
            double amount = Double.parseDouble(tbAmount1.getText());
            Date transDate = new Date();
            String staffId = lbStaff.getText();
            String cardId = tbCardNo.getText();
            GregorianCalendar calendarTrans = new GregorianCalendar();
            calendarTrans.setTime(transDate);
            XMLGregorianCalendar xmlTrans = null;
            try {
                xmlTrans = DatatypeFactory.newInstance().newXMLGregorianCalendar(calendarTrans);
            } catch (DatatypeConfigurationException ex) {
                Logger.getLogger(ConcessionFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            refund(amount, xmlTrans, staffId, cardId);
            lbMsg.setText("Refund successfully!");
        } else {
            lbMsg.setText("The reqired filed is missing!");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefundActionPerformed

    private void lbLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLogoutMouseClicked
        JOptionPane.showMessageDialog(this, "Confirm logout?", "Logout", JOptionPane.ERROR_MESSAGE);
        this.setVisible(false);
        LoginFrame lFrame = new LoginFrame();
        lFrame.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_lbLogoutMouseClicked

    private void lbLogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLogoutMousePressed
        JOptionPane.showMessageDialog(this, "Confirm logout?", "Logout", JOptionPane.ERROR_MESSAGE);
        this.setVisible(false);
        LoginFrame lFrame = new LoginFrame();
        lFrame.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_lbLogoutMousePressed
    private void quitOnNoReaderAttached() {
        JOptionPane.showMessageDialog(this, "No card reader is attached", "Reader Detected Failure", JOptionPane.ERROR_MESSAGE);
        this.setVisible(false);
        this.dispose();
    }

    private void checkCardPresent() {
        try {
            if (acr122uCardTerminal.isCardPresent()) {
                byte[] byteArrayReadUID = {(byte) 0xFF, (byte) 0xCA, (byte) 0x00, (byte) 0x00, (byte) 0x00};
                tbCardNo.setText(connectToCard(byteArrayReadUID));
                tbCardNo.setForeground(Color.GREEN);
                String cardNo = tbCardNo.getText();
                if (cardNo != null && !cardNo.equals("No Card Detected!")) { //check whether card has been detected
                    tbAmount1.setText(getRefundAmt(cardNo));
                } else {
                    lbMsg.setText("No Card Detected!");
                }
                tbAmount1.setVisible(true);
            } else {
                tbCardNo.setText("No Card Detected!");
                tbCardNo.setForeground(Color.RED);
            }
        } catch (Exception ex) {

        }
    }

    private String connectToCard(byte[] byteArrayReadUID) {
        try {
            acr122uCardTerminal.waitForCardPresent(0);
            Card card = acr122uCardTerminal.connect("T=1");
            CardChannel cardChannel = card.getBasicChannel();

            return send(byteArrayReadUID, cardChannel);
        } catch (Exception ex) {
            return "";
        }
    }

    public String send(byte[] command, CardChannel cardChannel) {
        String response = "";

        byte[] byteArrayResponse = new byte[258];
        ByteBuffer bufferedCommand = ByteBuffer.wrap(command);
        ByteBuffer bufferedResponse = ByteBuffer.wrap(byteArrayResponse);

        // output = The length of the received response APDU
        int output = 0;

        try {
            output = cardChannel.transmit(bufferedCommand, bufferedResponse);
        } catch (CardException ex) {
            ex.printStackTrace();
        }

        for (int i = 0; i < output; i++) {
            response += String.format("%02X", byteArrayResponse[i]);
        }

        return response;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RefundFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RefundFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RefundFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RefundFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RefundFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRefund;
    private javax.swing.JLabel lbAmount;
    private javax.swing.JLabel lbAmount1;
    private javax.swing.JLabel lbCardNo;
    private javax.swing.JLabel lbLogout;
    private javax.swing.JLabel lbMsg;
    private javax.swing.JLabel lbStaff;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbWelcome;
    private javax.swing.JLabel tbAmount;
    private javax.swing.JLabel tbAmount1;
    private javax.swing.JTextField tbCardNo;
    // End of variables declaration//GEN-END:variables

    private static String getRefundAmt(java.lang.String cardId) {
        ws.client.LoginWebService_Service service = new ws.client.LoginWebService_Service();
        ws.client.LoginWebService port = service.getLoginWebServicePort();
        return port.getRefundAmt(cardId);
    }

 /*   private static String getRefundAmt(java.lang.String cardId) {
        passenger.sessionbean.ws.LoginWebService_Service service = new passenger.sessionbean.ws.LoginWebService_Service();
        passenger.sessionbean.ws.LoginWebService port = service.getLoginWebServicePort();
        return port.getRefundAmt(cardId);
    }

    private static void refund(double amount, javax.xml.datatype.XMLGregorianCalendar transDate, java.lang.String staffId, java.lang.String cardId) {
        passenger.sessionbean.ws.LoginWebService_Service service = new passenger.sessionbean.ws.LoginWebService_Service();
        passenger.sessionbean.ws.LoginWebService port = service.getLoginWebServicePort();
        port.refund(amount, transDate, staffId, cardId);
    }*/

    private static void refund(double amount, javax.xml.datatype.XMLGregorianCalendar transDate, java.lang.String staffId, java.lang.String cardId) {
        ws.client.LoginWebService_Service service = new ws.client.LoginWebService_Service();
        ws.client.LoginWebService port = service.getLoginWebServicePort();
        port.refund(amount, transDate, staffId, cardId);
    }

}
