package citcardtopup;

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yuting
 */
public class SelectFrame extends javax.swing.JFrame {

    /**
     * Creates new form SelectFrame
     */
    public SelectFrame() {
        initComponents();
    }
    public SelectFrame(String username) {
        initComponents();
        lbStaff.setText(username);
        lbMsg.setText("");
        lbLogout.setText("Logout");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        lbTitle = new javax.swing.JLabel();
        rbTopUp = new javax.swing.JRadioButton();
        rbRefund = new javax.swing.JRadioButton();
        btnNext = new javax.swing.JButton();
        lbWelcome = new javax.swing.JLabel();
        lbStaff = new javax.swing.JLabel();
        lbMsg = new javax.swing.JLabel();
        lbLogout = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(716, 423));

        lbTitle.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        lbTitle.setText("Select Task to Perform");

        rbTopUp.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        rbTopUp.setText("Top Up");
        rbTopUp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbTopUpStateChanged(evt);
            }
        });

        rbRefund.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        rbRefund.setText("Refund");
        rbRefund.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbRefundStateChanged(evt);
            }
        });

        btnNext.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        lbWelcome.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbWelcome.setText("ID:");

        lbStaff.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbStaff.setText("Station Staff");

        lbMsg.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lbMsg.setForeground(new java.awt.Color(255, 0, 0));
        lbMsg.setText("msg");

        lbLogout.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbLogout.setText("Log Out");
        lbLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLogoutMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbLogoutMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbTopUp)
                                .addGap(70, 70, 70)
                                .addComponent(rbRefund))
                            .addComponent(btnNext, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(lbMsg)))
                .addContainerGap(227, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbWelcome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbStaff))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbLogout)
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbStaff)
                    .addComponent(lbWelcome)
                    .addComponent(lbLogout))
                .addGap(66, 66, 66)
                .addComponent(lbTitle)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbTopUp)
                    .addComponent(rbRefund))
                .addGap(18, 18, 18)
                .addComponent(lbMsg)
                .addGap(28, 28, 28)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbTopUpStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbTopUpStateChanged
        if (rbTopUp.isSelected()) {
            rbRefund.setEnabled(false);
        } else {
            rbRefund.setEnabled(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_rbTopUpStateChanged

    private void rbRefundStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbRefundStateChanged
        if (rbRefund.isSelected()) {
            rbTopUp.setEnabled(false);
        } else {
            rbTopUp.setEnabled(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_rbRefundStateChanged

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        String staff = lbStaff.getText();
        if (rbTopUp.isSelected() || rbRefund.isSelected()){
            if(rbTopUp.isSelected()){
                TopUpFrame tpFrame = new TopUpFrame(staff);
                tpFrame.setVisible(true);
                this.setVisible(false);
        }
            else if(rbRefund.isSelected()){
                RefundFrame rFrame = new RefundFrame(staff);
                rFrame.setVisible(true);
                this.setVisible(false);
            }
        }
        else{
            lbMsg.setText("Please select a function!");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNextActionPerformed

    private void lbLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLogoutMouseClicked
        JOptionPane.showMessageDialog(this, "Confirm logout?", "Logout", JOptionPane.ERROR_MESSAGE);
        this.setVisible(false);
        LoginFrame lFrame = new LoginFrame();
        lFrame.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_lbLogoutMouseClicked

    private void lbLogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLogoutMousePressed
        JOptionPane.showMessageDialog(this, "Confirm logout?", "Logout", JOptionPane.ERROR_MESSAGE);
        this.setVisible(false);
        LoginFrame lFrame = new LoginFrame();
        lFrame.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_lbLogoutMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lbLogout;
    private javax.swing.JLabel lbMsg;
    private javax.swing.JLabel lbStaff;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbWelcome;
    private javax.swing.JRadioButton rbRefund;
    private javax.swing.JRadioButton rbTopUp;
    // End of variables declaration//GEN-END:variables
}
