/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package citcardtopup;

import javax.swing.JOptionPane;

/**
 *
 * @author YuTing
 */
public class TopUpFrame extends javax.swing.JFrame {

    /**
     * Creates new form TopUpFrame
     */
    public TopUpFrame() {
        initComponents();
    }

    public TopUpFrame(String username) {
        initComponents();
        lbStaff.setText(username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbTitle = new javax.swing.JLabel();
        lbStaff = new javax.swing.JLabel();
        lbCardNo = new javax.swing.JLabel();
        rbConcession = new javax.swing.JRadioButton();
        rbVariable = new javax.swing.JRadioButton();
        btnNext = new javax.swing.JButton();
        lbMsg = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbLogout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTitle.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        lbTitle.setText("Select Top Up Option");

        lbStaff.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbStaff.setText("Station Staff");

        lbCardNo.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbCardNo.setText("Top Up Type: ");

        rbConcession.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        rbConcession.setText("Concession");
        rbConcession.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbConcessionItemStateChanged(evt);
            }
        });

        rbVariable.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        rbVariable.setText("Variable");
        rbVariable.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbVariableItemStateChanged(evt);
            }
        });

        btnNext.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        lbMsg.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbMsg.setForeground(new java.awt.Color(204, 0, 0));

        btnBack.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("ID:");

        lbLogout.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbLogout.setText("Log Out");
        lbLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLogoutMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbLogoutMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lbCardNo)
                        .addGap(18, 18, 18)
                        .addComponent(rbConcession)
                        .addGap(18, 18, 18)
                        .addComponent(rbVariable))
                    .addComponent(lbMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(18, 18, 18)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)))
                .addGap(0, 151, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(176, 176, 176))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbStaff)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbLogout)
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbStaff)
                    .addComponent(jLabel1)
                    .addComponent(lbLogout))
                .addGap(51, 51, 51)
                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCardNo)
                    .addComponent(rbConcession)
                    .addComponent(rbVariable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnNext))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbConcessionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbConcessionItemStateChanged
        if (rbConcession.isSelected()) {
            rbVariable.setEnabled(false);
        } else {
            rbVariable.setEnabled(true);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_rbConcessionItemStateChanged

    private void rbVariableItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbVariableItemStateChanged
        if (rbVariable.isSelected()) {
            rbConcession.setEnabled(false);
        } else {
            rbConcession.setEnabled(true);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_rbVariableItemStateChanged

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        String staff = lbStaff.getText();
        if (rbVariable.isSelected() || rbConcession.isSelected()){
            if(rbVariable.isSelected()){
                VariableFrame vFrame = new VariableFrame(staff, "Variable");
                vFrame.setVisible(true);
                this.setVisible(false);
            }
        
            else if(rbConcession.isSelected()){
                ConcessionFrame concessionFrame = new ConcessionFrame(staff,"Concession");
                concessionFrame.setVisible(true);
                this.setVisible(false);
            }
        }
        else{
            lbMsg.setText("Please select a top up type!");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.setVisible(false);
        SelectFrame sFrame = new SelectFrame(lbStaff.getText());
        sFrame.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void lbLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLogoutMouseClicked
        JOptionPane.showMessageDialog(this, "Confirm logout?", "Logout", JOptionPane.ERROR_MESSAGE);
        this.setVisible(false);
        LoginFrame lFrame = new LoginFrame();
        lFrame.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_lbLogoutMouseClicked

    private void lbLogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLogoutMousePressed
        JOptionPane.showMessageDialog(this, "Confirm logout?", "Logout", JOptionPane.ERROR_MESSAGE);
        this.setVisible(false);
        LoginFrame lFrame = new LoginFrame();
        lFrame.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_lbLogoutMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TopUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TopUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TopUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TopUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TopUpFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNext;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbCardNo;
    private javax.swing.JLabel lbLogout;
    private javax.swing.JLabel lbMsg;
    private javax.swing.JLabel lbStaff;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JRadioButton rbConcession;
    private javax.swing.JRadioButton rbVariable;
    // End of variables declaration//GEN-END:variables
}
