/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package citcardtopup;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.nio.ByteBuffer;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.smartcardio.Card;
import javax.smartcardio.CardChannel;
import javax.smartcardio.CardException;
import javax.smartcardio.CardTerminal;
import javax.smartcardio.TerminalFactory;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.xml.datatype.DatatypeConfigurationException;
import javax.xml.datatype.DatatypeFactory;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 *
 * @author yuting
 */
public class VariableFrame extends javax.swing.JFrame {

    /**
     * Creates new form VariableFrame
     */
    private CardTerminal acr122uCardTerminal = null;
    public VariableFrame() {
        initComponents();
    }

    public VariableFrame(String staff, String type) {
        initComponents();
        lbStaff.setText(staff);
        lbTopUpType.setText(type);
        lbMsg1.setText("");
        //lbMsg.setSize(230, 30);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbWelcome = new javax.swing.JLabel();
        lbStaff = new javax.swing.JLabel();
        lbTitle = new javax.swing.JLabel();
        lbAmount = new javax.swing.JLabel();
        lbType = new javax.swing.JLabel();
        lbTopUpType = new javax.swing.JLabel();
        lbCardNo = new javax.swing.JLabel();
        btnTopUp = new javax.swing.JButton();
        tbCardNo = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        lbMsg = new javax.swing.JLabel();
        tbAmount = new javax.swing.JLabel();
        btn5 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn50 = new javax.swing.JButton();
        lbLogout = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();
        lbTotalAmt = new javax.swing.JLabel();
        lbMsg1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lbWelcome.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbWelcome.setText("ID:");

        lbStaff.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbStaff.setText("Station Staff");

        lbTitle.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        lbTitle.setText("Select Top Up Value");

        lbAmount.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbAmount.setText("Amount: ");

        lbType.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbType.setText("Top Up Type: ");

        lbTopUpType.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbTopUpType.setText("Type");

        lbCardNo.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbCardNo.setText("Card Number: ");

        btnTopUp.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnTopUp.setText("Top Up");
        btnTopUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTopUpActionPerformed(evt);
            }
        });

        tbCardNo.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        btnBack.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lbMsg.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbMsg.setForeground(new java.awt.Color(204, 0, 0));

        tbAmount.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        btn5.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        btn5.setText("$5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn10.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        btn10.setText("$10");
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });

        btn50.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        btn50.setText("$50");
        btn50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn50ActionPerformed(evt);
            }
        });

        lbLogout.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbLogout.setText("Log Out");
        lbLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLogoutMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbLogoutMousePressed(evt);
            }
        });

        lbTotal.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbTotal.setText("Total: ");

        lbTotalAmt.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbTotalAmt.setText("0.0");

        lbMsg1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbMsg1.setForeground(new java.awt.Color(204, 0, 0));
        lbMsg1.setText("lbMsg");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 95, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbMsg)
                                        .addGap(120, 120, 120))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbCardNo)
                                            .addComponent(lbType))
                                        .addGap(30, 30, 30))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lbTotal)
                                            .addComponent(lbAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(38, 38, 38)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnTopUp))
                                        .addComponent(lbTopUpType, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(tbCardNo, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(tbAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btn10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btn50)
                                            .addGap(9, 9, 9)))
                                    .addComponent(lbTotalAmt)
                                    .addComponent(lbMsg1))
                                .addGap(142, 142, 142))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(168, 168, 168))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbWelcome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbStaff)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbLogout)
                        .addGap(56, 56, 56))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbStaff)
                    .addComponent(lbWelcome)
                    .addComponent(lbLogout))
                .addGap(52, 52, 52)
                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbType)
                    .addComponent(lbTopUpType))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(tbAmount))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCardNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbCardNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn5)
                    .addComponent(btn10)
                    .addComponent(btn50)
                    .addComponent(lbAmount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbMsg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTotal)
                    .addComponent(lbTotalAmt))
                .addGap(10, 10, 10)
                .addComponent(lbMsg1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnTopUp))
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        String staff = lbStaff.getText();
        TopUpFrame tpFrame = new TopUpFrame(staff);
        tpFrame.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnTopUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTopUpActionPerformed
        if (!tbCardNo.getText().equals("No Card Detected!") && lbTotalAmt.getText() != "0.0" && !tbCardNo.getText().equals("")) {
            String type = lbTopUpType.getText();
            double amount = Double.parseDouble(lbTotalAmt.getText());
            Date transDate = new Date();
            String staffId = lbStaff.getText();
            String cardId = tbCardNo.getText();
            GregorianCalendar calendarTrans = new GregorianCalendar();
            calendarTrans.setTime(transDate);
            XMLGregorianCalendar xmlTrans = null;
            try {
                xmlTrans = DatatypeFactory.newInstance().newXMLGregorianCalendar(calendarTrans);
            } catch (DatatypeConfigurationException ex) {
                Logger.getLogger(ConcessionFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            addValueTransaction(type, amount, xmlTrans, staffId, cardId);
            lbMsg1.setText("Top up successfully!");
        } else {
            lbMsg1.setText("The reqired filed is missing!");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTopUpActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
          try {
//            ActionListener actionListenerQuitOnNoReaderAttached = new ActionListener() {
//                public void actionPerformed(ActionEvent event) {
//                    quitOnNoReaderAttached();
//                }
//            };

//            Timer timerQuitOnNoReaderAttached = new Timer(5000, actionListenerQuitOnNoReaderAttached);
//            timerQuitOnNoReaderAttached.setRepeats(false);
//            timerQuitOnNoReaderAttached.start();

            TerminalFactory terminalFactory = TerminalFactory.getDefault();

            if (!terminalFactory.terminals().list().isEmpty()) {
                for (CardTerminal cardTerminal : terminalFactory.terminals().list()) {
                    if (cardTerminal.getName().contains("ACS ACR122")) {
                        acr122uCardTerminal = cardTerminal;

                        break;
                    }
                }

                if (acr122uCardTerminal != null) {
                    //timerQuitOnNoReaderAttached.stop();

                    //jTextFieldAttachedReader.setText(acr122uCardTerminal.getName());
                    ActionListener actionListenerCheckCardPresent = new ActionListener() {
                        public void actionPerformed(ActionEvent event) {
                            checkCardPresent();
                        }
                    };

                    Timer timerCheckCardPresent = new Timer(5000, actionListenerCheckCardPresent);
                    timerCheckCardPresent.setRepeats(true);
                    timerCheckCardPresent.start();

                    //JOptionPane.showMessageDialog(this, "ACS ACR122U Reader detected successfully", "Reader Detected Successful", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Unable to detect ACS ACR122U Reader", "Reader Detected Failure", JOptionPane.ERROR_MESSAGE);
                    this.setVisible(false);
                    this.dispose();
                }
            } else {
                JOptionPane.showMessageDialog(this, "No card reader is attached", "Reader Detected Failure", JOptionPane.ERROR_MESSAGE);
                this.setVisible(false);
                this.dispose();
            }
            } catch (Exception ex) {
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        double amount;
        if(lbTotalAmt.getText().equals("")){
            amount = 0;
        }else{
            amount = Double.parseDouble(lbTotalAmt.getText());
        }
        amount = amount + 5;
        lbTotalAmt.setText(String.valueOf(amount));
        // TODO add your handling code here:
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        double amount;
        if(lbTotalAmt.getText().equals("")){
            amount = 0;
        }else{
            amount = Double.parseDouble(lbTotalAmt.getText());
        }
        amount = amount + 10;
        lbTotalAmt.setText(String.valueOf(amount));
        // TODO add your handling code here:
    }//GEN-LAST:event_btn10ActionPerformed

    private void btn50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn50ActionPerformed
        double amount;
        if(lbTotalAmt.getText().equals("")){
            amount = 0;
        }else{
            amount = Double.parseDouble(lbTotalAmt.getText());
        }
        amount = amount + 50;
        lbTotalAmt.setText(String.valueOf(amount));
        // TODO add your handling code here:
    }//GEN-LAST:event_btn50ActionPerformed

    private void lbLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLogoutMouseClicked
        JOptionPane.showMessageDialog(this, "Confirm logout?", "Logout", JOptionPane.ERROR_MESSAGE);
        this.setVisible(false);
        LoginFrame lFrame = new LoginFrame();
        lFrame.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_lbLogoutMouseClicked

    private void lbLogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLogoutMousePressed
        JOptionPane.showMessageDialog(this, "Confirm logout?", "Logout", JOptionPane.ERROR_MESSAGE);
        this.setVisible(false);
        LoginFrame lFrame = new LoginFrame();
        lFrame.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_lbLogoutMousePressed
  private void quitOnNoReaderAttached() {
        JOptionPane.showMessageDialog(this, "No card reader is attached", "Reader Detected Failure", JOptionPane.ERROR_MESSAGE);
        this.setVisible(false);
        this.dispose();
    }

    private void checkCardPresent() {
        try {
            if (acr122uCardTerminal.isCardPresent()) {
                byte[] byteArrayReadUID = {(byte) 0xFF, (byte) 0xCA, (byte) 0x00, (byte) 0x00, (byte) 0x00};
                tbCardNo.setText(connectToCard(byteArrayReadUID));
                tbCardNo.setForeground(Color.GREEN);
            } else {
                tbCardNo.setText("No Card Detected!");
                tbCardNo.setForeground(Color.RED);
            }
        } catch (Exception ex) {
        }
    }

    private String connectToCard(byte[] byteArrayReadUID) {
        try {
            acr122uCardTerminal.waitForCardPresent(0);
            Card card = acr122uCardTerminal.connect("T=1");
            CardChannel cardChannel = card.getBasicChannel();

            return send(byteArrayReadUID, cardChannel);
        } catch (Exception ex) {
            return "";
        }
    }

    public String send(byte[] command, CardChannel cardChannel) {
        String response = "";

        byte[] byteArrayResponse = new byte[258];
        ByteBuffer bufferedCommand = ByteBuffer.wrap(command);
        ByteBuffer bufferedResponse = ByteBuffer.wrap(byteArrayResponse);

        // output = The length of the received response APDU
        int output = 0;

        try {
            output = cardChannel.transmit(bufferedCommand, bufferedResponse);
        } catch (CardException ex) {
            ex.printStackTrace();
        }

        for (int i = 0; i < output; i++) {
            response += String.format("%02X", byteArrayResponse[i]);
        }

        return response;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VariableFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VariableFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VariableFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VariableFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VariableFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn50;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnTopUp;
    private javax.swing.JLabel lbAmount;
    private javax.swing.JLabel lbCardNo;
    private javax.swing.JLabel lbLogout;
    private javax.swing.JLabel lbMsg;
    private javax.swing.JLabel lbMsg1;
    private javax.swing.JLabel lbStaff;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbTopUpType;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JLabel lbTotalAmt;
    private javax.swing.JLabel lbType;
    private javax.swing.JLabel lbWelcome;
    private javax.swing.JLabel tbAmount;
    private javax.swing.JTextField tbCardNo;
    // End of variables declaration//GEN-END:variables

    private static void addValueTransaction(java.lang.String type, double amount, javax.xml.datatype.XMLGregorianCalendar transDate, java.lang.String staffId, java.lang.String cardId) {
        ws.client.LoginWebService_Service service = new ws.client.LoginWebService_Service();
        ws.client.LoginWebService port = service.getLoginWebServicePort();
        port.addValueTransaction(type, amount, transDate, staffId, cardId);
    }

   /* private static void addValueTransaction(java.lang.String type, double amount, javax.xml.datatype.XMLGregorianCalendar transDate, java.lang.String staffId, java.lang.String cardId) {
        passenger.sessionbean.ws.LoginWebService_Service service = new passenger.sessionbean.ws.LoginWebService_Service();
        passenger.sessionbean.ws.LoginWebService port = service.getLoginWebServicePort();
        port.addValueTransaction(type, amount, transDate, staffId, cardId);
    }*/


}
